name: event-expander
version: '1.0.0'

ghc-options: -Wall

executables:
  event-expander:
    dependencies:
    - base
    - event-expander
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executables

library:
  dependencies:
    - base
    - bytestring
    - cassava
    - classy-prelude
    - finite-typelits
    - text
    - vector
  source-dirs: library
