name: event-expander
version: '1.0.0'

ghc-options: -Wall

executables:
  event-expander:
    dependencies:
    - base
    - event-expander
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executables

library:
  dependencies:
    - attoparsec
    - base
    - bytestring
    - cassava
    - classy-prelude
    - closed
    - finite-typelits
    - fixed-vector
    - lens
    - template-haskell
    - text
    - unordered-containers
    - vector
  source-dirs: library

tests:
  test:
    dependencies:
    - base
    - classy-prelude
    - event-expander
    - hspec-attoparsec
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Test.hs
    source-dirs: tests
